export enum ActionTypes {
  COMPLETE_TASK = "COMPLETE_TASK",
  REMOVE_TASK = "REMOVE_TASK",
  ADD_TASK = "ADD_TASK",
  CHANGE_INPUT = "CHANGE_INPUT",
  GET_DESCRIPTION = "GET_DESCRIPTION",
  EDIT_TASK = "EDIT_TASK",
}
 